### ISSUE TITLE
Add example using Homeyscript

### ISSUE THREAD

**Issue by gertlind** [wizz666/OpenEpaperLink-Homey-Pro#1]
Having examples using Homeyscript would be nice.

**Comment by wizz666** [comment]
If you run a homeyscript that generates a tag, you can use it in the parsed version card.
I'm going to test with garbage collection via homeyscript which generates a tag that I use in the code that I run in the parsed version card and hope it will generate the right information when I get closer to collection day this Thursday.

**Comment by wizz666** [comment]
https://github.com/wizz666/OpenEpaperLink-Homey-Pro/blob/main/HomeyScript.md

**Comment by wizz666** [comment]
https://github.com/wizz666/OpenEpaperLink-Homey-Pro/blob/main/HomeyScript.md
